### ISSUE TITLE
Github Deployment

### ISSUE THREAD

**Issue by arabiu033** [arabiu033/Portfolio-Project#11]
Deployed Successfully Already.
Here is the link to the deployment
`https://arabiu033.github.io/Portfolio-Project/`

Also, Updated the readme.md file to reflect the changes.

**Comment by zhadier** [comment]
## Hi @arabiu033  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>

# Congratulations! 🎉 

✔️ No linter errors
✔️ Professional pull request title and description

### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
